theme: bulma-clean-theme

# Site Settings
fixed_navbar: top
permalink: pretty
footer_menu: footer_menu
locale: "en"
lang: en
languages: ["en", "de"]
default_lang: "en"
exclude_from_localization: ["assets", "javascript", "images", "css", "public", "sitemap.xml", "customer-images.txt", "Gemfile", "robots.txt", "CNAME"]
parallel_localization: false
direction: ltr # left to right
google_analytics: # UA-xxxxxxx
title: "ExplicIT"
description: "We bridge the gap between strategy and execution"
url: "https://explicitconsulting.at" # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. "/blog"
repository: "ExplicITConsulting/ExplicITConsulting.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
favicon: "/assets/images/explicit consulting, color on black, favicon.png"
navbar_logo: "/assets/images/explicit consulting, color on transparent, company only.png"
navbar_logo_alt: "ExplicIT"
force_theme: #light

# SEO Related
google_site_verification:
bing_site_verification:
naver_site_verification:
yandex_site_verification:
baidu_site_verification:

sass:
  style: compressed
  source_dir: _sass
  sourcemap: never

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: page
      image: "/assets/images/explicit consulting, color on black.png"
      hero_height: is-small
      hero_darken: false
      lang: en
      locale: en

include:
  - ".well-known"
