theme                    : bulma-clean-theme

# Site Settings
fixed_navbar             : top
permalink                : pretty
footer_menu              : footer_menu
locale                   : "en"
lang                     : en
languages                : ["en"]
default_lang             : en
direction                : ltr # left to right
google_analytics         : # UA-xxxxxxx
title                    : "ExplicIT Consulting"
description              : "We bridge the gap between strategy and execution"
url                      : "https://explicitconsulting.at" # the base hostname & protocol for your site
site.url                 : "https://explicitconsulting.at" # the base hostname & protocol for your site
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "ExplicITConsulting/ExplicITConsulting.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
favicon                  : "/assets/images/explicit consulting, color on black, favicon.png"
force_theme              : #light

# SEO Related
google_site_verification :
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :




# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from


# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

sass:
  style: compressed
  source_dir: _sass

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: page
      image: "/assets/images/explicit consulting, color on black.png"
      hero_image: "/assets/images/background, vietnam golden bridge.jpg"
      hero_height: is-small
      hero_darken: true

include:
  - ".well-known"
