name: 'search-engines-urls-push'
on:
  workflow_dispatch:
  schedule:
    # Set the schedule time
    - cron: '15 */2 * * *'

jobs:
  check-and-submit:
    runs-on: ubuntu-latest
    steps:
    - name: search-engines-urls-push@latest
      uses: 3Alan/search-engines-urls-push@v0.2.3
      with:
        site: ${{ secrets.SITE }}
        sitemap: ${{ secrets.SITEMAP }}
        bing-token: ${{ secrets.BING_TOKEN }}
        google-client-email: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
        google-private-key: ${{ secrets.GOOGLE_PRIVATE_KEY }}
